### ISSUE TITLE
Speed control loop

### ISSUE THREAD

**Issue by tyler123durden** [OpHaCo/hoverbot#1]
Hello, 
I've also started with some hoverboard hacks, here are my projects: 
https://github.com/tyler123durden/hoverboard-hardware
https://developer.mbed.org/users/Thomas_H/code/HoverboardTest/

I started some tests with a closed loop control for the speed. But at certain points I've got some strange behaviour. Especially when wheels should rotate in different directions or speeds. It is possible to do this but control loop behaves kind of sluggish. Do you have done such tests?
Here are some diagrams: 
![ramp up different](https://cloud.githubusercontent.com/assets/2444429/20039815/478b4f10-a44b-11e6-943e-46b003211d07.png)
![ramp up same](https://cloud.githubusercontent.com/assets/2444429/20039816/4fb55276-a44b-11e6-839c-4fcd1a12650e.png)

**Comment by Lahorde** [comment]
As you can see, in my sketch I control both motors. I can :

* rotate cleanly motor 1 in clockwise while motor 2 is in other direction (in this case, I send same angle values to mother board)
* rotate cleanly motor 1 in non-clockwise while motor 2 is in other direction (in this case, I send same angle values to mother board)
in these configurations, I can control motor speed.

But when I have both motors rotating in same direction (in this case I give a positive angular position on left daughterboard UART and a negative one on right daughterboard UART), first it rotates well, but after some seconds, it speeds up until reaching max speed. I think something misses in this case. It's quite strange, I'm wondering if my motherboard is not buggy. May be solution is elsewhere : calibration, other sensor...
I've tried different calibrations values and it dit not change anything. I told Drew Nibble if he got same issue and he said "I believe that the acceleration when both wheels are going the same direction is a bug in the closed loop controller. It does not seem to happen under load (although I have not tested extensively)"
 I must test this hypothesis on a true hoverboard! May be you have tested it? 

So I should get in few days a new motherboard : http://www.skywalkers.paris/pieces-detachees-hoverboard/91-carte-mere-taotao-hoverboard-adulte-7091046701306.html 
and an hoverboard. 

I think we want to make same thing : closed loop speed control using this cheap motherboard, and I'm sure we will manage to do it!

**Comment by tyler123durden** [comment]
OK, I see. In my tests same direction means different sign for both sides and different direction (hoverboard rotates) means same sign. 
The motor board seems to have kind of PI characteristic. As you see in same direction plot. You have to reduce input to 0 or nearly to hold same speed. I think this is your speed up at constant input. 
But this does not apply for different directions (same sign). Here it has more kind of P characteristic. Which does also apply if both wheel speeds differ to much then. 
Will try to get some plots for open loop speed response. But maybe I've got another firmware version because I must send following sequence, which has 2 more bytes. 

            oMotorRight.putc(256);
            oMotorRight.putc(_Controlloop[RIGHT].u & 0xFF);
            oMotorRight.putc((_Controlloop[RIGHT].u >> 8) & 0xFF);
            oMotorRight.putc(_Controlloop[RIGHT].u & 0xFF);
            oMotorRight.putc((_Controlloop[RIGHT].u >> 8) & 0xFF);
            oMotorRight.putc(85);
            oMotorRight.putc(82);
            oMotorRight.putc(82);

I've not tested my setup under load, will try to test it that weekend.

**Comment by Lahorde** [comment]
" As you see in same direction plot. You have to reduce input to 0 or nearly to hold same speed.", that's it, above a given threshold, speeds keeps increasing until reaching max speed. You are true with PI behaviour, but physically, it's quite hard to understand, but I think it's because I never rode an hoverboard. Maybe in forward direction, rotating feets rotate first gyroscope daughterboards causing hoverboard speed up, maybe during this acceleration gyroscope daughteboards come back to a flat position... I should test it in some few days!

**Comment by Lahorde** [comment]
I will test tomorrow an integral control, 
In pseudo code :

    setForwardSpeed(speed)
       setRightSpeed(speed*ramp_up_coef)
       setLeftSpeed(speed*ramp_up_coef)
       startTimer(duration = 1/ramp_up_coeff)

    onTimerExpired()
       setRightSpeed(0 calibration value)
       setLeftSpeed(0 calibration value)

**Comment by Lahorde** [comment]
Got it and tested :
```
/** 
 * Integral control of speed
 */
void goForward(uint16_t speed)
{
  float RAMP_UP_FACTOR = 1;
  uint16_t  speedRampUp = (speed*RAMP_UP_FACTOR);
        

  uint16_t lFrame[6] = {256, speedRampUp & 0xff, speedRampUp >> 8 & 0xff, speedRampUp & 0xff, speedRampUp >> 8 & 0xff, 85};
  uint16_t rFrame[6] = {256, (-speedRampUp) & 0xff, (-speedRampUp) >> 8 & 0xff, (-speedRampUp) & 0xff, (-speedRampUp) >> 8 & 0xff, 85};

  Serial.print(millis()); 
  Serial.print(": applying speed of ");
  Serial.println(speedRampUp);
  
  uint32_t timeStart = millis();
  while((millis() - timeStart) < (1/RAMP_UP_FACTOR)*10000)
  {
    for(uint8_t index = 0; index < 6; index++)
    {
      DAUGHTER_BOARD_SERIAL_SIM_R.write9bit(rFrame[index]);
      DAUGHTER_BOARD_SERIAL_SIM_L.write9bit(lFrame[index]); 
    }
  }
  
  speedRampUp = _calValue;
  
  lFrame[1] = _calValue & 0xff;
  lFrame[2] = _calValue >> 8 & 0xff;
  lFrame[3] = lFrame[1];
  lFrame[4] = lFrame[2];

  rFrame[1] = -_calValue & 0xff;   
  rFrame[2] = -_calValue >> 8 & 0xff;
  rFrame[3] = rFrame[1];
  rFrame[4] = rFrame[2];

  
  Serial.print(millis()); 
  Serial.print(": applying speed of ");
  Serial.println(_calValue);

  while(1){
    for(uint8_t index = 0; index < 6; index++)
    {
      DAUGHTER_BOARD_SERIAL_SIM_R.write9bit(rFrame[index]);
      DAUGHTER_BOARD_SERIAL_SIM_L.write9bit(lFrame[index]); 
    }
  }
}
```

In order to get clean control we must also hack calibration process to have a 0 calibration!

**Comment by Lahorde** [comment]
Look at https://github.com/OpHaCo/hoverbot/blob/master/hoverbot_embedded_software/teensy_hoverboard/teensy_hoverboard.ino for an updated code. Some work in code must be done to have a clean control, I will close issue when I will finish it.

**Comment by tyler123durden** [comment]
Great to see it works! 
So maybe you could also try controlling both wheels with different speeds and look at the response. 
For the calibration process if would guess all is done in the motor controller and no communication to the gyro board is done. The motor board just sets the zero point to the received gyro inputs. So just send 0 to the motorboard and start calibration should do the trick. 
As mentioned above a simple PI controller works quite good for speed control except if wheel speed differs to much.

**Comment by Lahorde** [comment]
Yes, calibration can definitely been done manually, as you said,  just set a 0 output on your MCU UARTs when you do calibration. Next week I will test it deeper, integration factor must be precisely identified.

**Comment by KevinPlaridel** [comment]
Hello Lahorde. I've been trying to make my hoverboard works and I tried your sketch, but there is error. Can you help me?

I put the hoverboard.h and brushless_hall_sensor.h in 
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3

but the error is 
```
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3\hoverboard.cpp:81:33: error: 'SERIAL_9N1' was not declared in this scope
   _p_gyro1Serial->begin (26300, SERIAL_9N1);  // 9 bits mode
                                 ^
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3\hoverboard.cpp: In member function 'Hoverboard::EHoverboardErr Hoverboard::setSpeed(float, float)':
```

Hope you can help. Thank you

![image](https://cloud.githubusercontent.com/assets/7366803/21078223/8c201ada-bfa2-11e6-96f4-06f0bf39dba9.png)

**Comment by KevinPlaridel** [comment]
SERIAL_9N1 is solved. but when I added 
```
#include <hoverboard.h>
#include <brushless_hall_sensor.h>
```
"idlecontrol() was not declared" said in the error

```
hoverboard_original:36: error: 'idleControl' was not declared in this scope
     idleControl();
```

**Comment by Lahorde** [comment]
I've updated code, refer https://github.com/OpHaCo/hoverbot/blob/master/hoverbot_embedded_software/teensy_hoverboard/hoverboard/hoverboard.cpp
I've not yet implemented any PID. Some coding / cleaning must still be done but now everything is possible. Next step is to improve hoverboard control and to make an hoverbot shield.
